version: "3"
services:
  BDD1:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: simplon
        #- POSTGRES_DB=safeDB
  web1:
    build: .  #laisser le build est préferable m si on met l'image de son repo docker, pour éviter de re-build à chq fois.
    depends_on:
      - BDD1
    image: php:apache
    #image:bosimplon/simplon_project-safe 
    environment:
      DATABASE_URL: pgsql://postgres:simplon@BDD1:5432/safeDB
    volumes:
      - /home/bhuguenin/Documents/dev/dev_CtrPro/project-safe/skeleton:/app
      - /home/bhuguenin/App/VirtualHostApache.conf:/etc/apache2/sites-available/000-default.conf
           
       




#docker run --name web1 -v /home/bhuguenin/Documents/dev/dev_CtrPro/project-safe/skeleton:/app -v /home/bhuguenin/App/VirtualHostApache.conf:/etc/apache2/sites-available/000-default.conf -e #DATABASE_URL=pgsql://postgres:simplon@172.17.0.3:5432/safeDB -d php:apache


#docker run --name BDD1 -e POSTGRES_PASSWORD=simplon -d postgres
